logging:
  ##file:
  ##    name: log/Sboard.log
  level:
    jdbc:
      connection: info
      resultsettable: info
      sqlonly: info
      sqltiming: info
    org:
      hibernate: info
      springframework:
        security: info
    root: info
server:
  servlet:
    context-path: /cinema
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "!Q2w3e4r"
    url: jdbc:mysql://3.37.127.212:3306/Cinema
    username: "cinema"

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_spl: true
        use_sql_comments: true
  security:
    user:
      name: user
      password: 1234
  thymeleaf:
    cache: false
    #개발
    #prefix : file:src/main/resources/templates
    # 배포
    prefix: classpath:/templates

    mvc:
      static-path-pattern: "/static/**"

  # 파일 업로드 설정
  servlet:
    multipart:
      location: thumbs/
      max-file-size: 10MB



upload :
    path :
      files : files/
      thumbs : thumbs/
      banners : banners/


# mybatis 설정
mybatis:
  mapper-locations: classpath:mappers/**/*.xml